### ISSUE TITLE
KeyError during Blueprint.plan

### ISSUE THREAD

**Issue by dpguthrie** [teej/titan#9]
I'm currently receiving a KeyError when [fetch_session](https://github.com/teej/titan/blob/371364c8d10eb596da2b323deec0632c3d37c08c/titan/blueprint.py#L324) is called when running `Blueprint.plan`, specifically when tags are being retrieved:

https://github.com/teej/titan/blob/371364c8d10eb596da2b323deec0632c3d37c08c/titan/data_provider.py#L175

Just looking at the [Snowflake docs](https://docs.snowflake.com/en/sql-reference/sql/show-tags#examples), the column names appear to be `database_name` and `schema_name`.

I'm using the new 0.1.0 release also:
![image](https://github.com/teej/titan/assets/10198967/90dc03aa-831d-4800-b999-b162a1a80f1e)

**Comment by teej** [comment]
I'll fix this in v0.1.1
